name: dev_pay
description: A Flutter SDK for Devpay Payment Gateway Get your API Keys at https://devpay.io
version: 0.0.1
homepage: https://devpay.io/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/card.png
    - assets/powerd_by.png
